"""Shared project metadata, safe recoverable archives, and idempotent operations.

Navigation entries are archived as catalog records; shared navigation files stay
in place. Tutor directories move to outputs/interactive-tutor/archives and return
to their original location on restore. No source material or log is deleted.
"""
from pathlib import Path
from contextlib import ExitStack
import copy
import os
import re
import subprocess
from .structured_io import read_json, write_json, json_digest
from .timestamp import iso_timestamp, parse_filename_timestamp
from .file_transaction import project_lock
from .workflow_checkpoint import WorkflowCheckpoint, create_run_directory

TRANSITIONS = {
    'prepared': ('validating',), 'validating': ('executing', 'paused_error'),
    'executing': ('verifying', 'paused_error'), 'verifying': ('completed', 'paused_error'),
    'paused_error': ('validating',), 'completed': (),
}


def registry_path(root):
    return Path(root) / 'outputs/interactive-tutor/project-management.json'


def registry(root):
    path = registry_path(root)
    result = read_json(path) if path.is_file() else {'schema_version': '1.0', 'entries': {}}
    if not isinstance(result, dict): raise ValueError('项目管理登记损坏')
    if result.get('schema_version') != '1.0' or not isinstance(result.get('entries'), dict):
        raise ValueError('项目管理登记损坏')
    for pid, entry in result['entries'].items():
        validate_id(pid)
        if not isinstance(entry, dict) or entry.get('kind') not in ('tutor', 'navigation') or not isinstance(entry.get('archived'), bool):
            raise ValueError('项目管理登记无效')
        if not isinstance(entry.get('title'), str) or not entry['title'].strip(): raise ValueError('项目管理名称无效')
        if entry['archived']:
            if not isinstance(entry.get('archived_at'), str) or not isinstance(entry.get('original_path'), str): raise ValueError('项目归档登记无效')
            safe_path(root, entry['original_path'])
            if entry['kind'] == 'tutor' and entry.get('archive_path') != f'outputs/interactive-tutor/archives/{pid}': raise ValueError('项目归档路径无效')
    return result


def validate_id(pid):
    if not isinstance(pid, str) or not re.fullmatch(r'(?:nav-)?\d{8}T\d{6}(?:_\d+)?', pid): raise ValueError('项目 ID 无效')


def entry(root, pid): return registry(root)['entries'].get(pid, {})


def ensure_active(root, pid):
    if entry(root, pid).get('archived'): raise ValueError('项目已归档，请先恢复')


def timestamps(model):
    created = model.get('created_at')
    if not created:
        # An ID is generated by timestamp.py at creation, unlike a filesystem mtime.
        try: created = parse_filename_timestamp(model.get('project_id', ''))
        except ValueError: pass
    learned = model.get('last_learning_at')
    if not learned:
        events = [e['at'] for e in model.get('events', []) if isinstance(e.get('at'), str) and
                  re.search(r'answer|review|question|publish_lesson|feedback|adaptation|podcast_verified_and_lesson_published', e.get('event', '')) and
                  not (e.get('event') == 'publish_lesson' and e.get('to') == 'podcast_required')]
        learned = max(events, default=None)
    return created, learned


def activity_digest(model, excluded=()):
    return json_digest({
        'lessons': [{'id': l['lesson_id'], 'content': l.get('content'), 'answers': l.get('answers'),
                     'review': l.get('review'), 'feedback': l.get('learner_feedback')} for l in model.get('lessons', []) if l['lesson_id'] not in excluded and l.get('content') and (not l.get('podcast', {}).get('requested') or l['podcast'].get('status') == 'completed')],
        'discussions': model.get('question_discussions', []), 'adaptation': model.get('next_adaptation'),
    })


def mark_learning_activity(project, model):
    path = Path(project) / 'artifacts/学习路线.json'
    if path.is_file():
        pending = {l['lesson_id'] for l in model.get('lessons', []) if l.get('podcast', {}).get('requested') and l['podcast'].get('status') != 'completed'}
        if activity_digest(read_json(path), pending) != activity_digest(model, pending):
            model['last_learning_at'] = iso_timestamp()


def safe_path(root, raw):
    from .learning_project import safe_path as resolve
    root = Path(root).resolve(); path = resolve(root,raw)
    if path == root: raise ValueError('项目路径越界')
    return path


def archived_projects(root):
    return [{'id': pid, 'title': e['title'], 'kind': e['kind'], 'archivedAt': e['archived_at']}
            for pid, e in registry(root)['entries'].items() if e['archived']]



def operation_checkpoint(root, action_id):
    if not isinstance(action_id, str) or not re.fullmatch(r'[A-Za-z0-9_-]{1,100}', action_id): raise ValueError('操作 ID 无效')
    for path in (Path(root)/'logs/interactive-tutor/runs').glob('*/project-management/state.json'):
        if read_json(path).get('actionId') == action_id: return path
    return None

def operate(root, pid, path, kind, payload, revision):
    """Replay the same action ID after failure; checkpoint binds the exact request."""
    from . import learning_project as lp
    root = Path(root).resolve(); validate_id(pid)
    if not isinstance(payload, dict): raise ValueError('项目操作必须为 JSON 对象')
    if not isinstance(payload.get('expectedRevision'), str) or not payload['expectedRevision']: raise ValueError('项目版本无效')
    operation = payload.get('operation'); action_id = payload.get('actionId')
    if operation not in ('rename', 'archive', 'restore', 'open-directory'): raise ValueError('项目操作无效')
    fields = {'operation', 'actionId', 'expectedRevision'} | ({'title'} if operation == 'rename' else set())
    if set(payload) != fields or not isinstance(action_id, str) or not re.fullmatch(r'[A-Za-z0-9_-]{1,100}', action_id):
        raise ValueError('项目操作字段无效')
    if kind not in ('tutor', 'navigation'): raise ValueError('项目类型无效')
    path = safe_path(root, path)
    signature = json_digest([pid, payload])
    with project_lock(registry_path(root).with_suffix('.lock'), 'project-management'), ExitStack() as locks:
        checkpoint = operation_checkpoint(root,action_id)
        run = checkpoint.parent if checkpoint else create_run_directory(root/'logs/interactive-tutor/runs')/'project-management'
        flow = WorkflowCheckpoint(TRANSITIONS, run, resume=True, restart_completed=False)
        flow.update(actionId=action_id)
        if flow.details.get('signature') not in (None, signature): raise ValueError('操作 ID 冲突')
        target_binding = {'id': pid, 'path': str(path.relative_to(root)), 'kind': kind}
        if flow.details.get('target') not in (None, target_binding): raise ValueError('操作目标冲突')
        flow.update(target=target_binding)
        if flow.state == 'completed': return flow.details['result']
        recovering = flow.details.get('validated', False)
        if flow.state not in ('prepared', 'paused_error'): flow.move('paused_error', reason='恢复中断操作')
        try:
            flow.move('validating', signature=signature)
            data = registry(root); previous = data['entries'].get(pid, {})
            if recovering and json_digest(previous) not in (flow.details.get('base_entry'), flow.details.get('desired_entry')):
                raise ValueError('项目版本冲突，中断后项目已改变，请刷新后重试')
            if kind == 'tutor':
                record = flow.details.get('record') or previous
                source = path if path.is_dir() else safe_path(root,record['archive_path']) if record.get('archive_path') else path
                locks.enter_context(lp.lock(source, allow_archived=True))
                source_model = lp.load(source)
                if source_model['project_id'] != pid: raise ValueError('项目目录与项目 ID 不一致')
                source_digest = json_digest(source_model)
                if recovering and source_digest not in (flow.details.get('base_model'), flow.details.get('applied_model')):
                    raise ValueError('项目版本冲突，中断后学习记录已改变，请刷新后重试')
                if not recovering: flow.update(base_model=source_digest)
            else:
                navigation_digest = json_digest(read_json(path))
                if recovering and navigation_digest != flow.details.get('base_navigation'):
                    raise ValueError('项目版本冲突，中断后共享导航已改变，请刷新后重试')
                if not recovering: flow.update(base_navigation=navigation_digest)
            current_revision = (revision() if callable(revision) else revision) if not recovering else None
            if not recovering and payload['expectedRevision'] != current_revision: raise ValueError('项目版本冲突，请刷新后重试')
            if operation == 'rename':
                title = payload['title']
                if not isinstance(title, str) or not title.strip() or len(title.strip()) > 200 or re.search(r'[\x00-\x1f\x7f]', title):
                    raise ValueError('项目名称须为 1～200 个字符且不能含控制字符')
                title = title.strip()
            else: title = previous.get('title', '')
            if operation == 'restore':
                if not recovering and not previous.get('archived'): raise ValueError('项目未归档')
                path = safe_path(root, previous['original_path'])
            elif not recovering:
                ensure_active(root, pid)
            flow.move('executing', validated=True, base_entry=flow.details.get('base_entry') if recovering else json_digest(previous))
            if operation == 'open-directory':
                folder = path.parent if kind == 'navigation' else path
                if not folder.is_dir(): raise FileNotFoundError('项目目录不存在')
                if os.name == 'nt': os.startfile(str(folder))
                else: subprocess.Popen(['open' if os.sys.platform == 'darwin' else 'xdg-open', str(folder)])
            elif operation == 'rename':
                if kind == 'tutor':
                    model = lp.load(path); model['title'] = title
                    from .learning_config import load_config
                    if json_digest(model) != flow.details.get('applied_model'):
                        lp.save(path, model, model.get('render_config') or load_config('interactive-tutor', root)['config'])
                    flow.update(applied_model=json_digest(lp.load(path)))
                data['entries'][pid] = {**previous, 'kind': kind, 'title': title, 'archived': False, 'last_action_id': action_id}
                flow.update(desired_entry=json_digest(data['entries'][pid]))
                write_json(registry_path(root), data)
            elif operation in ('archive', 'restore'):
                record = flow.details.get('record')
                if operation == 'archive' and record is None:
                    title = lp.load(path)['title'] if kind == 'tutor' else previous.get('title', read_json(path)['title'])
                    record = {**previous, 'kind': kind, 'title': title, 'archived': True,
                              'archived_at': iso_timestamp(), 'original_path': str(path.relative_to(root)),
                              'archive_path': f'outputs/interactive-tutor/archives/{pid}' if kind == 'tutor' else None}
                    flow.update(record=record)
                if operation == 'restore':
                    record = flow.details.get('record') or previous
                    flow.update(record=record)
                if kind == 'tutor':
                    archive = safe_path(root, record['archive_path'])
                    source, target = (path, archive) if operation == 'archive' else (archive, path)
                    if source.is_relative_to(target) or target.is_relative_to(source): raise ValueError('归档目录与原目录不能互相包含')
                    if source.exists() and target.exists(): raise ValueError('恢复/归档目标已存在，拒绝覆盖')
                    if source.exists():
                        # Never relocate the shared navigation, logs, or workspace via a custom project directory.
                        model = lp.load(source)
                        for raw in (model['navigation_json'], model['run_dir']):
                            if safe_path(root, raw).is_relative_to(source): raise ValueError('项目目录包含共享导航或日志，不能移动')
                        navigation = read_json(safe_path(root, model['navigation_json']))
                        for material in navigation.get('sources', []):
                            raw = material.get('path')
                            if raw and safe_path(root, raw).is_relative_to(source):
                                raise ValueError('项目目录包含原始材料，不能移动')
                        target.parent.mkdir(parents=True, exist_ok=True)
                        source.rename(target)
                    if not target.is_dir(): raise FileNotFoundError('归档/恢复目录不存在')
                    if lp.load(target)['project_id'] != pid: raise ValueError('归档/恢复目标与项目 ID 不一致')
                data['entries'][pid] = {**record, 'archived': operation == 'archive', 'last_action_id': action_id}
                flow.update(desired_entry=json_digest(data['entries'][pid]))
                write_json(registry_path(root), data)
            flow.move('verifying')
            if operation != 'open-directory' and registry(root)['entries'].get(pid) != data['entries'][pid]:
                raise ValueError('项目管理结果不一致')
            result = {'id': pid, 'operation': operation, 'status': 'completed'}
            flow.move('completed', result=result)
            return result
        except Exception:
            if 'paused_error' in TRANSITIONS.get(flow.state, ()): flow.move('paused_error')
            raise


def detail(model, directory, kind):
    created, learned = timestamps(model)
    active = [l for l in model['lessons'] if not l.get('archived')]
    def counts(rows):
        total = len(rows); done = sum(r['status'] == 'completed' for r in rows)
        return {'total': total, 'completed': done, 'learning': sum(r['status'] in ('awaiting_answer', 'retry') for r in rows),
                'pending': sum(r['status'] == 'pending' for r in rows),
                'skipped': sum(r['status'] == 'skipped' or r.get('skip', False) for r in rows),
                'completionRate': done / total if total else None}
    units = list(model['unit_progress'].values())
    masters = [r['mastery'] for r in units if r.get('mastery') is not None and r.get('evidence_refs')]
    current = next((l for l in active if l['lesson_id'] == model.get('current_lesson_id')), None)
    from .learning_content import coverage_rows
    return {'kind': kind, 'directory': str(directory), 'createdAt': created, 'lastLearningAt': learned,
            'currentLesson': {'id': current['lesson_id'], 'number': current['number'], 'title': current['title']} if current else None,
            'statistics': {'units': counts(units), 'lessons': counts(active),
                           'main': counts([l for l in active if l['track'] == 'main']),
                           'branch': counts([l for l in active if l['track'] == 'branch']),
                           'mastery': sum(masters) / len(masters) if masters else None},
            'materials': [{'id': s.get('source_id', ''), 'title': s.get('title') or Path(s.get('path', '')).name} for s in model.get('sources', [])],
            'coverage': ([{**point, 'lessons': []} for point in model.get('material_points', [])] if kind == 'navigation' else coverage_rows(model)) if model.get('material_points') else []}
